use banksystem;

insert into Bank values('清华大学支行', '北京 海淀', 100000000, '/media/images/清华大学.jpg');
insert into Bank values('北京大学支行', '北京 海淀', 100000000, '/media/images/北京大学.jpg');
insert into Bank values('复旦大学支行', '上海 杨浦', 100000000,  '/media/images/复旦大学.jpg');
insert into Bank values('上海交通大学支行', '上海 闵行', 100000000, '/media/images/上海交通大学.jpg');
insert into Bank values('浙江大学支行', '杭州 玉泉', 100000000, '/media/images/浙江大学.jpg');
insert into Bank values('中国科学技术大学支行', '合肥 包河', 100000000, '/media/images/中科大.jpg' );
insert into Bank values('中国科学技术大学高新支行', '合肥 蜀山高新技术开发区', 100000000, '/media/images/中科大.jpg');
insert into Bank values('南京大学鼓楼支行', '南京 鼓楼', 100000000, '/media/images/南京大学.jpg');
insert into Bank values('南京大学仙林支行', '南京 栖霞', 100000000, '/media/images/南京大学.jpg');
insert into Bank values('华中科技大学支行', '武汉 洪山', 100000000, '/media/images/华中科技大学.jpg');
insert into Bank values('中山大学支行', '广州 海珠', 100000000, '/media/images/中山大学.jpg');
insert into Bank values('武汉大学支行', '武汉 洪山', 100000000, '/media/images/武汉大学.jpg');

-- 为每个银行支行添加部门
insert into department values('清华大学支行总行', '清华大学支行', '总行', '总行');
insert into department values('清华大学支行财务部', '清华大学支行', '财务部', '财务部');
insert into department values('清华大学支行人事部', '清华大学支行', '人事部', '人事部');
insert into department values('清华大学支行业务部', '清华大学支行', '业务部', '业务部');
insert into department values('清华大学支行风险管理部', '清华大学支行', '风险管理部', '风险管理部');
insert into department values('清华大学支行客户服务部', '清华大学支行', '客户服务部', '客户服务部');
insert into department values('清华大学支行信贷部', '清华大学支行', '信贷部', '信贷部');
insert into department values('清华大学支行理财部', '清华大学支行', '理财部', '理财部');
insert into department values('清华大学支行贷款部', '清华大学支行', '贷款部', '贷款部');
insert into department values('清华大学支行存款部', '清华大学支行', '存款部', '存款部');
insert into department values('清华大学支行信用卡部', '清华大学支行', '信用卡部', '信用卡部');
insert into department values('清华大学支行资产管理部', '清华大学支行', '资产管理部', '资产管理部');
insert into department values('清华大学支行审计部', '清华大学支行', '审计部', '审计部');
insert into department values('清华大学支行法律部', '清华大学支行', '法律部', '法律部');
insert into department values('清华大学支行信息技术部', '清华大学支行', '信息技术部', '信息技术部');
insert into department values('清华大学支行网络安全部', '清华大学支行', '网络安全部', '网络安全部');
insert into department values('清华大学支行数据中心', '清华大学支行', '数据中心', '数据中心');
insert into department values('清华大学支行保安部', '清华大学支行', '保安部', '保安部');
insert into department values('清华大学支行后勤部', '清华大学支行', '后勤部', '后勤部');
insert into department values('清华大学支行宣传部', '清华大学支行', '宣传部', '宣传部');
insert into department values('清华大学支行人力资源部', '清华大学支行', '人力资源部', '人力资源部');   

insert into department values('北京大学支行总行', '北京大学支行', '总行', '总行');
insert into department values('北京大学支行财务部', '北京大学支行', '财务部', '财务部');
insert into department values('北京大学支行人事部', '北京大学支行', '人事部', '人事部');
insert into department values('北京大学支行业务部', '北京大学支行', '业务部', '业务部');
insert into department values('北京大学支行风险管理部', '北京大学支行', '风险管理部', '风险管理部');
insert into department values('北京大学支行客户服务部', '北京大学支行', '客户服务部', '客户服务部');
insert into department values('北京大学支行信贷部', '北京大学支行', '信贷部', '信贷部');
insert into department values('北京大学支行理财部', '北京大学支行', '理财部', '理财部');
insert into department values('北京大学支行贷款部', '北京大学支行', '贷款部', '贷款部');
insert into department values('北京大学支行存款部', '北京大学支行', '存款部', '存款部');
insert into department values('北京大学支行信用卡部', '北京大学支行', '信用卡部', '信用卡部');
insert into department values('北京大学支行结算部', '北京大学支行', '结算部', '结算部');
insert into department values('北京大学支行清算部', '北京大学支行', '清算部', '清算部');
insert into department values('北京大学支行资产管理部', '北京大学支行', '资产管理部', '资产管理部');
insert into department values('北京大学支行风险控制部', '北京大学支行', '风险控制部', '风险控制部');
insert into department values('北京大学支行监察部', '北京大学支行', '监察部', '监察部');
insert into department values('北京大学支行维修部', '北京大学支行', '维修部', '维修部');
insert into department values('北京大学支行保洁部', '北京大学支行', '保洁部', '保洁部');
insert into department values('北京大学支行保安部', '北京大学支行', '保安部', '保安部');
insert into department values('北京大学支行后勤部', '北京大学支行', '后勤部', '后勤部');
insert into department values('北京大学支行宣传部', '北京大学支行', '宣传部', '宣传部');
insert into department values('北京大学支行人力资源部', '北京大学支行', '人力资源部', '人力资源部');

insert into department values('复旦大学支行总行', '复旦大学支行', '总行', '总行');
insert into department values('复旦大学支行财务部', '复旦大学支行', '财务部', '财务部');
insert into department values('复旦大学支行人事部', '复旦大学支行', '人事部', '人事部');
insert into department values('复旦大学支行业务部', '复旦大学支行', '业务部', '业务部');
insert into department values('复旦大学支行风险管理部', '复旦大学支行', '风险管理部', '风险管理部');
insert into department values('复旦大学支行客户服务部', '复旦大学支行', '客户服务部', '客户服务部');
insert into department values('复旦大学支行信贷部', '复旦大学支行', '信贷部', '信贷部');
insert into department values('复旦大学支行理财部', '复旦大学支行', '理财部', '理财部');
insert into department values('复旦大学支行贷款部', '复旦大学支行', '贷款部', '贷款部');
insert into department values('复旦大学支行存款部', '复旦大学支行', '存款部', '存款部');
insert into department values('复旦大学支行信用卡部', '复旦大学支行', '信用卡部', '信用卡部');
insert into department values('复旦大学支行资产管理部', '复旦大学支行', '资产管理部', '资产管理部');
insert into department values('复旦大学支行审计部', '复旦大学支行', '审计部', '审计部');
insert into department values('复旦大学支行法律部', '复旦大学支行', '法律部', '法律部');
insert into department values('复旦大学支行信息技术部', '复旦大学支行', '信息技术部', '信息技术部');
insert into department values('复旦大学支行网络安全部', '复旦大学支行', '网络安全部', '网络安全部');
insert into department values('复旦大学支行数据中心', '复旦大学支行', '数据中心', '数据中心');
insert into department values('复旦大学支行保安部', '复旦大学支行', '保安部', '保安部');
insert into department values('复旦大学支行后勤部', '复旦大学支行', '后勤部', '后勤部');
insert into department values('复旦大学支行宣传部', '复旦大学支行', '宣传部', '宣传部');
insert into department values('复旦大学支行人力资源部', '复旦大学支行', '人力资源部', '人力资源部');

insert into department values('上海交通大学支行总行', '上海交通大学支行', '总行', '总行');
insert into department values('上海交通大学支行财务部', '上海交通大学支行', '财务部', '财务部');
insert into department values('上海交通大学支行人事部', '上海交通大学支行', '人事部', '人事部');
insert into department values('上海交通大学支行业务部', '上海交通大学支行', '业务部', '业务部');
insert into department values('上海交通大学支行风险管理部', '上海交通大学支行', '风险管理部', '风险管理部');
insert into department values('上海交通大学支行客户服务部', '上海交通大学支行', '客户服务部', '客户服务部');
insert into department values('上海交通大学支行信贷部', '上海交通大学支行', '信贷部', '信贷部');
insert into department values('上海交通大学支行理财部', '上海交通大学支行', '理财部', '理财部');
insert into department values('上海交通大学支行贷款部', '上海交通大学支行', '贷款部', '贷款部');
insert into department values('上海交通大学支行存款部', '上海交通大学支行', '存款部', '存款部');
insert into department values('上海交通大学支行信用卡部', '上海交通大学支行', '信用卡部', '信用卡部');
insert into department values('上海交通大学支行资产管理部', '上海交通大学支行', '资产管理部', '资产管理部');
insert into department values('上海交通大学支行审计部', '上海交通大学支行', '审计部', '审计部');
insert into department values('上海交通大学支行法律部', '上海交通大学支行', '法律部', '法律部');
insert into department values('上海交通大学支行信息技术部', '上海交通大学支行', '信息技术部', '信息技术部');
insert into department values('上海交通大学支行网络安全部', '上海交通大学支行', '网络安全部', '网络安全部');
insert into department values('上海交通大学支行数据中心', '上海交通大学支行', '数据中心', '数据中心');
insert into department values('上海交通大学支行保安部', '上海交通大学支行', '保安部', '保安部');
insert into department values('上海交通大学支行后勤部', '上海交通大学支行', '后勤部', '后勤部');
insert into department values('上海交通大学支行宣传部', '上海交通大学支行', '宣传部', '宣传部');
insert into department values('上海交通大学支行人力资源部', '上海交通大学支行', '人力资源部', '人力资源部');

insert into department values('浙江大学支行总行', '浙江大学支行', '总行', '总行');
insert into department values('浙江大学支行财务部', '浙江大学支行', '财务部', '财务部');
insert into department values('浙江大学支行人事部', '浙江大学支行', '人事部', '人事部');
insert into department values('浙江大学支行业务部', '浙江大学支行', '业务部', '业务部');
insert into department values('浙江大学支行风险管理部', '浙江大学支行', '风险管理部', '风险管理部');
insert into department values('浙江大学支行客户服务部', '浙江大学支行', '客户服务部', '客户服务部');
insert into department values('浙江大学支行信贷部', '浙江大学支行', '信贷部', '信贷部');
insert into department values('浙江大学支行理财部', '浙江大学支行', '理财部', '理财部');
insert into department values('浙江大学支行贷款部', '浙江大学支行', '贷款部', '贷款部');
insert into department values('浙江大学支行存款部', '浙江大学支行', '存款部', '存款部');
insert into department values('浙江大学支行信用卡部', '浙江大学支行', '信用卡部', '信用卡部');
insert into department values('浙江大学支行资产管理部', '浙江大学支行', '资产管理部', '资产管理部');
insert into department values('浙江大学支行审计部', '浙江大学支行', '审计部', '审计部');
insert into department values('浙江大学支行法律部', '浙江大学支行', '法律部', '法律部');
insert into department values('浙江大学支行信息技术部', '浙江大学支行', '信息技术部', '信息技术部');
insert into department values('浙江大学支行网络安全部', '浙江大学支行', '网络安全部', '网络安全部');
insert into department values('浙江大学支行数据中心', '浙江大学支行', '数据中心', '数据中心');
insert into department values('浙江大学支行保安部', '浙江大学支行', '保安部', '保安部');
insert into department values('浙江大学支行后勤部', '浙江大学支行', '后勤部', '后勤部');
insert into department values('浙江大学支行宣传部', '浙江大学支行', '宣传部', '宣传部');
insert into department values('浙江大学支行人力资源部', '浙江大学支行', '人力资源部', '人力资源部');

insert into department values('中国科学技术大学支行总行', '中国科学技术大学支行', '总行', '总行');
insert into department values('中国科学技术大学支行财务部', '中国科学技术大学支行', '财务部', '财务部');
insert into department values('中国科学技术大学支行人事部', '中国科学技术大学支行', '人事部', '人事部');
insert into department values('中国科学技术大学支行业务部', '中国科学技术大学支行', '业务部', '业务部');
insert into department values('中国科学技术大学支行风险管理部', '中国科学技术大学支行', '风险管理部', '风险管理部');
insert into department values('中国科学技术大学支行客户服务部', '中国科学技术大学支行', '客户服务部', '客户服务部');
insert into department values('中国科学技术大学支行信贷部', '中国科学技术大学支行', '信贷部', '信贷部');
insert into department values('中国科学技术大学支行理财部', '中国科学技术大学支行', '理财部', '理财部');
insert into department values('中国科学技术大学支行贷款部', '中国科学技术大学支行', '贷款部', '贷款部');
insert into department values('中国科学技术大学支行存款部', '中国科学技术大学支行', '存款部', '存款部');
insert into department values('中国科学技术大学支行信用卡部', '中国科学技术大学支行', '信用卡部', '信用卡部');
insert into department values('中国科学技术大学支行资产管理部', '中国科学技术大学支行', '资产管理部', '资产管理部');
insert into department values('中国科学技术大学支行审计部', '中国科学技术大学支行', '审计部', '审计部');
insert into department values('中国科学技术大学支行法律部', '中国科学技术大学支行', '法律部', '法律部');
insert into department values('中国科学技术大学支行信息技术部', '中国科学技术大学支行', '信息技术部', '信息技术部');
insert into department values('中国科学技术大学支行网络安全部', '中国科学技术大学支行', '网络安全部', '网络安全部');
insert into department values('中国科学技术大学支行数据中心', '中国科学技术大学支行', '数据中心', '数据中心');
insert into department values('中国科学技术大学支行保安部', '中国科学技术大学支行', '保安部', '保安部');
insert into department values('中国科学技术大学支行后勤部', '中国科学技术大学支行', '后勤部', '后勤部');
insert into department values('中国科学技术大学支行宣传部', '中国科学技术大学支行', '宣传部', '宣传部');
insert into department values('中国科学技术大学支行人力资源部', '中国科学技术大学支行', '人力资源部', '人力资源部');

insert into department values('中国科学技术大学高新支行总行', '中国科学技术大学高新支行', '总行', '总行');
insert into department values('中国科学技术大学高新支行财务部', '中国科学技术大学高新支行', '财务部', '财务部');
insert into department values('中国科学技术大学高新支行人事部', '中国科学技术大学高新支行', '人事部', '人事部');
insert into department values('中国科学技术大学高新支行业务部', '中国科学技术大学高新支行', '业务部', '业务部');
insert into department values('中国科学技术大学高新支行风险管理部', '中国科学技术大学高新支行', '风险管理部', '风险管理部');
insert into department values('中国科学技术大学高新支行客户服务部', '中国科学技术大学高新支行', '客户服务部', '客户服务部');
insert into department values('中国科学技术大学高新支行信贷部', '中国科学技术大学高新支行', '信贷部', '信贷部');
insert into department values('中国科学技术大学高新支行理财部', '中国科学技术大学高新支行', '理财部', '理财部');
insert into department values('中国科学技术大学高新支行贷款部', '中国科学技术大学高新支行', '贷款部', '贷款部');
insert into department values('中国科学技术大学高新支行存款部', '中国科学技术大学高新支行', '存款部', '存款部');
insert into department values('中国科学技术大学高新支行信用卡部', '中国科学技术大学高新支行', '信用卡部', '信用卡部');
insert into department values('中国科学技术大学高新支行资产管理部', '中国科学技术大学高新支行', '资产管理部', '资产管理部');
insert into department values('中国科学技术大学高新支行审计部', '中国科学技术大学高新支行', '审计部', '审计部');
insert into department values('中国科学技术大学高新支行法律部', '中国科学技术大学高新支行', '法律部', '法律部');
insert into department values('中国科学技术大学高新支行信息技术部', '中国科学技术大学高新支行', '信息技术部', '信息技术部');
insert into department values('中国科学技术大学高新支行网络安全部', '中国科学技术大学高新支行', '网络安全部', '网络安全部');
insert into department values('中国科学技术大学高新支行数据中心', '中国科学技术大学高新支行', '数据中心', '数据中心');
insert into department values('中国科学技术大学高新支行保安部', '中国科学技术大学高新支行', '保安部', '保安部');
insert into department values('中国科学技术大学高新支行后勤部', '中国科学技术大学高新支行', '后勤部', '后勤部');
insert into department values('中国科学技术大学高新支行宣传部', '中国科学技术大学高新支行', '宣传部', '宣传部');
insert into department values('中国科学技术大学高新支行人力资源部', '中国科学技术大学高新支行', '人力资源部', '人力资源部');

insert into department values('南京大学鼓楼支行总行', '南京大学鼓楼支行', '总行', '总行');
insert into department values('南京大学鼓楼支行财务部', '南京大学鼓楼支行', '财务部', '财务部');
insert into department values('南京大学鼓楼支行人事部', '南京大学鼓楼支行', '人事部', '人事部');
insert into department values('南京大学鼓楼支行业务部', '南京大学鼓楼支行', '业务部', '业务部');
insert into department values('南京大学鼓楼支行风险管理部', '南京大学鼓楼支行', '风险管理部', '风险管理部');
insert into department values('南京大学鼓楼支行客户服务部', '南京大学鼓楼支行', '客户服务部', '客户服务部');
insert into department values('南京大学鼓楼支行信贷部', '南京大学鼓楼支行', '信贷部', '信贷部');
insert into department values('南京大学鼓楼支行理财部', '南京大学鼓楼支行', '理财部', '理财部');
insert into department values('南京大学鼓楼支行贷款部', '南京大学鼓楼支行', '贷款部', '贷款部');
insert into department values('南京大学鼓楼支行存款部', '南京大学鼓楼支行', '存款部', '存款部');
insert into department values('南京大学鼓楼支行信用卡部', '南京大学鼓楼支行', '信用卡部', '信用卡部');
insert into department values('南京大学鼓楼支行资产管理部', '南京大学鼓楼支行', '资产管理部', '资产管理部');
insert into department values('南京大学鼓楼支行审计部', '南京大学鼓楼支行', '审计部', '审计部');
insert into department values('南京大学鼓楼支行法律部', '南京大学鼓楼支行', '法律部', '法律部');
insert into department values('南京大学鼓楼支行信息技术部', '南京大学鼓楼支行', '信息技术部', '信息技术部');
insert into department values('南京大学鼓楼支行网络安全部', '南京大学鼓楼支行', '网络安全部', '网络安全部');
insert into department values('南京大学鼓楼支行数据中心', '南京大学鼓楼支行', '数据中心', '数据中心');
insert into department values('南京大学鼓楼支行保安部', '南京大学鼓楼支行', '保安部', '保安部');
insert into department values('南京大学鼓楼支行后勤部', '南京大学鼓楼支行', '后勤部', '后勤部');
insert into department values('南京大学鼓楼支行宣传部', '南京大学鼓楼支行', '宣传部', '宣传部');
insert into department values('南京大学鼓楼支行人力资源部', '南京大学鼓楼支行', '人力资源部', '人力资源部');

insert into department values('南京大学仙林支行总行', '南京大学仙林支行', '总行', '总行');
insert into department values('南京大学仙林支行财务部', '南京大学仙林支行', '财务部', '财务部');
insert into department values('南京大学仙林支行人事部', '南京大学仙林支行', '人事部', '人事部');
insert into department values('南京大学仙林支行业务部', '南京大学仙林支行', '业务部', '业务部');
insert into department values('南京大学仙林支行风险管理部', '南京大学仙林支行', '风险管理部', '风险管理部');
insert into department values('南京大学仙林支行客户服务部', '南京大学仙林支行', '客户服务部', '客户服务部');
insert into department values('南京大学仙林支行信贷部', '南京大学仙林支行', '信贷部', '信贷部');
insert into department values('南京大学仙林支行理财部', '南京大学仙林支行', '理财部', '理财部');
insert into department values('南京大学仙林支行贷款部', '南京大学仙林支行', '贷款部', '贷款部');
insert into department values('南京大学仙林支行存款部', '南京大学仙林支行', '存款部', '存款部');
insert into department values('南京大学仙林支行信用卡部', '南京大学仙林支行', '信用卡部', '信用卡部');
insert into department values('南京大学仙林支行资产管理部', '南京大学仙林支行', '资产管理部', '资产管理部');
insert into department values('南京大学仙林支行审计部', '南京大学仙林支行', '审计部', '审计部');
insert into department values('南京大学仙林支行法律部', '南京大学仙林支行', '法律部', '法律部');
insert into department values('南京大学仙林支行信息技术部', '南京大学仙林支行', '信息技术部', '信息技术部');
insert into department values('南京大学仙林支行网络安全部', '南京大学仙林支行', '网络安全部', '网络安全部');
insert into department values('南京大学仙林支行数据中心', '南京大学仙林支行', '数据中心', '数据中心');
insert into department values('南京大学仙林支行保安部', '南京大学仙林支行', '保安部', '保安部');
insert into department values('南京大学仙林支行后勤部', '南京大学仙林支行', '后勤部', '后勤部');
insert into department values('南京大学仙林支行宣传部', '南京大学仙林支行', '宣传部', '宣传部');
insert into department values('南京大学仙林支行人力资源部', '南京大学仙林支行', '人力资源部', '人力资源部');

insert into department values('华中科技大学支行总行', '华中科技大学支行', '总行', '总行');
insert into department values('华中科技大学支行财务部', '华中科技大学支行', '财务部', '财务部');
insert into department values('华中科技大学支行人事部', '华中科技大学支行', '人事部', '人事部');
insert into department values('华中科技大学支行业务部', '华中科技大学支行', '业务部', '业务部');
insert into department values('华中科技大学支行风险管理部', '华中科技大学支行', '风险管理部', '风险管理部');
insert into department values('华中科技大学支行客户服务部', '华中科技大学支行', '客户服务部', '客户服务部');
insert into department values('华中科技大学支行信贷部', '华中科技大学支行', '信贷部', '信贷部');
insert into department values('华中科技大学支行理财部', '华中科技大学支行', '理财部', '理财部');
insert into department values('华中科技大学支行贷款部', '华中科技大学支行', '贷款部', '贷款部');
insert into department values('华中科技大学支行存款部', '华中科技大学支行', '存款部', '存款部');
insert into department values('华中科技大学支行信用卡部', '华中科技大学支行', '信用卡部', '信用卡部');
insert into department values('华中科技大学支行资产管理部', '华中科技大学支行', '资产管理部', '资产管理部');
insert into department values('华中科技大学支行审计部', '华中科技大学支行', '审计部', '审计部');
insert into department values('华中科技大学支行法律部', '华中科技大学支行', '法律部', '法律部');
insert into department values('华中科技大学支行信息技术部', '华中科技大学支行', '信息技术部', '信息技术部');
insert into department values('华中科技大学支行网络安全部', '华中科技大学支行', '网络安全部', '网络安全部');
insert into department values('华中科技大学支行数据中心', '华中科技大学支行', '数据中心', '数据中心');
insert into department values('华中科技大学支行保安部', '华中科技大学支行', '保安部', '保安部');
insert into department values('华中科技大学支行后勤部', '华中科技大学支行', '后勤部', '后勤部');
insert into department values('华中科技大学支行宣传部', '华中科技大学支行', '宣传部', '宣传部');
insert into department values('华中科技大学支行人力资源部', '华中科技大学支行', '人力资源部', '人力资源部');

insert into department values('中山大学支行总行', '中山大学支行', '总行', '总行');
insert into department values('中山大学支行财务部', '中山大学支行', '财务部', '财务部');
insert into department values('中山大学支行人事部', '中山大学支行', '人事部', '人事部');
insert into department values('中山大学支行业务部', '中山大学支行', '业务部', '业务部');
insert into department values('中山大学支行风险管理部', '中山大学支行', '风险管理部', '风险管理部');
insert into department values('中山大学支行客户服务部', '中山大学支行', '客户服务部', '客户服务部');
insert into department values('中山大学支行信贷部', '中山大学支行', '信贷部', '信贷部');
insert into department values('中山大学支行理财部', '中山大学支行', '理财部', '理财部');
insert into department values('中山大学支行贷款部', '中山大学支行', '贷款部', '贷款部');
insert into department values('中山大学支行存款部', '中山大学支行', '存款部', '存款部');
insert into department values('中山大学支行信用卡部', '中山大学支行', '信用卡部', '信用卡部');
insert into department values('中山大学支行资产管理部', '中山大学支行', '资产管理部', '资产管理部');
insert into department values('中山大学支行审计部', '中山大学支行', '审计部', '审计部');
insert into department values('中山大学支行法律部', '中山大学支行', '法律部', '法律部');
insert into department values('中山大学支行信息技术部', '中山大学支行', '信息技术部', '信息技术部');
insert into department values('中山大学支行网络安全部', '中山大学支行', '网络安全部', '网络安全部');
insert into department values('中山大学支行数据中心', '中山大学支行', '数据中心', '数据中心');
insert into department values('中山大学支行保安部', '中山大学支行', '保安部', '保安部');
insert into department values('中山大学支行后勤部', '中山大学支行', '后勤部', '后勤部');
insert into department values('中山大学支行宣传部', '中山大学支行', '宣传部', '宣传部');
insert into department values('中山大学支行人力资源部', '中山大学支行', '人力资源部', '人力资源部');

insert into department values('武汉大学支行总行', '武汉大学支行', '总行', '总行');
insert into department values('武汉大学支行财务部', '武汉大学支行', '财务部', '财务部');
insert into department values('武汉大学支行人事部', '武汉大学支行', '人事部', '人事部');
insert into department values('武汉大学支行业务部', '武汉大学支行', '业务部', '业务部');
insert into department values('武汉大学支行风险管理部', '武汉大学支行', '风险管理部', '风险管理部');
insert into department values('武汉大学支行客户服务部', '武汉大学支行', '客户服务部', '客户服务部');
insert into department values('武汉大学支行信贷部', '武汉大学支行', '信贷部', '信贷部');
insert into department values('武汉大学支行理财部', '武汉大学支行', '理财部', '理财部');
insert into department values('武汉大学支行贷款部', '武汉大学支行', '贷款部', '贷款部');
insert into department values('武汉大学支行存款部', '武汉大学支行', '存款部', '存款部');
insert into department values('武汉大学支行信用卡部', '武汉大学支行', '信用卡部', '信用卡部');
insert into department values('武汉大学支行资产管理部', '武汉大学支行', '资产管理部', '资产管理部');
insert into department values('武汉大学支行审计部', '武汉大学支行', '审计部', '审计部');
insert into department values('武汉大学支行法律部', '武汉大学支行', '法律部', '法律部');
insert into department values('武汉大学支行信息技术部', '武汉大学支行', '信息技术部', '信息技术部');
insert into department values('武汉大学支行网络安全部', '武汉大学支行', '网络安全部', '网络安全部');
insert into department values('武汉大学支行数据中心', '武汉大学支行', '数据中心', '数据中心');
insert into department values('武汉大学支行保安部', '武汉大学支行', '保安部', '保安部');
insert into department values('武汉大学支行后勤部', '武汉大学支行', '后勤部', '后勤部');
insert into department values('武汉大学支行宣传部', '武汉大学支行', '宣传部', '宣传部');
insert into department values('武汉大学支行人力资源部', '武汉大学支行', '人力资源部', '人力资源部');

-- 添加客户
